### ISSUE TITLE
change `mount.rs` find_parent_mount from pub to private

### ISSUE THREAD

**Issue by lengrongfu** [youki-dev/youki#2814]
The current `find_parent_mount` method is only in `impl Mount` use, we can change to `private fn` from `pub fn`.
https://github.com/containers/youki/blob/4d4ce7c3710d1ed8f155adf23fb62dc672197043/crates/libcontainer/src/rootfs/mount.rs#L614

**Comment by YJDoc2** [comment]
Note that this change would likely be a breaking change, so PR should be labeled accordingly, along with changelog info.

**Comment by utam0k** [comment]
@Mossaka Do you use this function in runwasi?

**Comment by Mossaka** [comment]
No, it's not used in runwasi. However, I would be more careful in making breaking changes if we don't have a strong motivation.

**Comment by lengrongfu** [comment]
Thanks every body suggestion, we can hold this issue, keep watch, and then decide how to resolve.

**Comment by YJDoc2** [comment]
Hey, I think we should make a decision on this, primarily because I feel this is cluttering the issue list without any clear way to resolve. 

I see two possible paths for this -

1. keep the function public : I don't think there will be any significant overhead for this, we can continue to let things be as-is.
2. mark the function as deprecated, and remove it after 2 releases. This way if anyone is using this function will get a deprecation warning at compile time, and if they mention their use to use we can revert the deprecation back and keep it pub. Else we can remove the pub after 2 releases.

I'm fine with either, but would prefer to choose one and close this issue.

**Comment by utam0k** [comment]
@YJDoc2 Thanks for your suggestion. Leave it public as we are not troubled by this and it does not affect performance. It is not productive to do this sort of organisation now for all methods.

**Comment by utam0k** [comment]
Feel free to reopen it.
