### ISSUE TITLE
Move to an independent organization

### ISSUE THREAD

**Issue by utam0k** [youki-dev/youki#2962]
Since youki has become the CNCF Sandbox, youki needs to be moved to a separate org. I have many fond memories of my work with containers org here. Unfortunately, youki repo needs to become independent. Thanks, `containers`.

https://github.com/cncf/sandbox/issues/297#issuecomment-2429180184

**Comment by utam0k** [comment]
@containers/youki-maintainers `youki` org has already been taken. I've reserved `youki-dev` org. WDYT? or `containers-rs,` but it might lead to a bit of confusion.

**Comment by YJDoc2** [comment]
> I've reserved youki-dev org. WDYT? or containers-rs, but it might lead to a bit of confusion.

Sounds good to me :+1: Given that there are already two well-known orgs `containers` and `opencontainers` adding `containers-rs` will cause more confusion, so `youki-dev` seems perfect 💙

**Comment by yihuaf** [comment]
`youki-dev` makes sense.

**Comment by jprendes** [comment]
I like `youki-dev` :-)
Thanks `containers` org for giving us a home until now!

**Comment by utam0k** [comment]
I'll wait for your opinion until Tuesday at least.

**Comment by utam0k** [comment]
I'll move youki under youki-dev.

**Comment by utam0k** [comment]
Done. We are here https://github.com/youki-dev/youki

**Comment by hegerdes** [comment]
Hi, just as a suggestion: Would you mind to pin this issue for the next couple of months?

I was a bit confused this morning because my automation broke (totally my fault - should have added the `-L` flag to curl) and only found the update docs issue (#2967) at first and nothing about why or when this moved. 

Pinning or mentioning is the the Readme might help some people with fragil automation like mine to be sure is the same repo and why it moved.

Congratulation to becoming CNCF Sandbox, though 😊

**Comment by YJDoc2** [comment]
>Pinning or mentioning is the the Readme might help some people with fragil automation like mine to be sure is the same repo and why it moved.

Thanks for the suggestion. I have pinned the issue for now, might update the readme in the other issue that is open. Sorry for your broken automations :)

> Congratulation to becoming CNCF Sandbox, though 😊

Thank you!

**Comment by utam0k** [comment]
Thanks! I've published the announcements about it in this org instead of pinning the issue.
